name: mt_env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - ipykernel
  - ipython
  - jupyter
  - python=3.11
  - pandas
  - matplotlib
  - seaborn
  - lxml
  - plotly
